change_list.html: add default base_template value to fix django-compress
django-import-export/django-import-export pull request #1605
Opened 2023-08-08 10:20 UTC by PetrDlouhy

**Problem**

The django-compress raises following errors during run of `compress` management command:
```
# python manage.py compress
Compressing... 
Error parsing template admin/import_export/change_list_import.html: Invalid template name in 'extends' tag: ''. Got this from the 'base_change_list_template' variable.
Error parsing template admin/import_export/change_list_import_export.html: Invalid template name in 'extends' tag: ''. Got this from the 'base_change_list_template' variable.
Error parsing template admin/import_export/change_list_export.html: Invalid template name in 'extends' tag: ''. Got this from the 'base_change_list_template' variable.
EError parsing template admin/import_export/change_list.html: Invalid template name in 'extends' tag: ''. Got this from the 'base_change_list_template' variable.
```

The problem is, that the parser in `django-compress` doesn't set the `base_change_list_template` variable.

**Solution**

I set default value for the variable in the template.

**Acceptance Criteria**

I have added test that would fail if the default value is not set.

2023-08-30 22:00 UTC, girishkumarkh commented
@matthewhegarty would it be possible to merge this please? 🙏

2023-08-31 08:24 UTC, matthewhegarty commented
I will review as soon as I can

2023-09-06 12:47 UTC, matthewhegarty requested changes
Thanks @PetrDlouhy 

It looks like [django-compress](https://code.google.com/archive/p/django-compress) is no longer maintained.  Does this fix relate to [django-compressor](https://django-compressor.readthedocs.io/)?

I checked out your branch and noticed that the test still passes, even when you remove the default from `change_list.html` - please could you double check and if necessary fix the test?

2023-09-13 17:58 UTC, matthewhegarty commented
Hi Petr - if you are able to look into the review comments on this, we should be able to get it into the forthcoming 3.3.0 release
thanks

2023-09-19 13:29 UTC, matthewhegarty commented
Thanks - I think you must have taken your branch off `release-4` - I've changed the target branch to `release-4`, so hopefully it shows your changes correctly now.

2023-09-19 13:43 UTC, matthewhegarty commented
Looks like you have to pull `release-4` branch, and then merge into `fix_compress`.  We have a failing test on 'admin/import_export/change_list.html'.  Can you get the tests to run locally?

2023-09-19 16:19 UTC, matthewhegarty reviewed
I don't understand why `ie_base_change_list_template` would be invalid at this point.  Why is the 'default' clause needed?  Doesn't  `ie_base_change_list_template` get set in `init_change_list_template()`, and could we resolve this issue in ` `ie_base_change_list_template``?

2023-09-20 14:00 UTC, PetrDlouhy commented
@matthewhegarty The `django-compressor` runs through all templates in project and tries to interpret them. It has no variable set, so that `ie_base_change_list_template` is `None`. In result it is not able to interpret the template which fails and warning is thrown.

2023-09-20 14:03 UTC, matthewhegarty commented
ok thanks

2023-09-20 14:04 UTC, merged

2025-09-17 21:04 UTC, domdinicola commented
I'm getting 404... wouldn't be better

{% with template_name=ie_base_change_list_template|default:"admin/change_list.html" %}
  {% extends template_name %}
{% endwith %}