refactored test_admin_integration.py
django-import-export/django-import-export pull request #1662
Opened 2023-10-22 18:13 UTC by PrashansaChaudhary

**Problem**

What problem have you solved?
Refactored the test_admin_integration.py

**Solution**

How did you solve the problem?
Segregated tests based on their functionality and logical grouping

**Acceptance Criteria**

Have you written tests? Have you included screenshots of your changes if applicable?
Did you document your changes?

2023-10-22 18:18 UTC, matthewhegarty commented
Hi - thanks for resubmitting.  I've converted the PR to 'draft' whilst it is still in progress.

2023-10-27 08:34 UTC, matthewhegarty commented
Please can you install [pre-commit](https://github.com/django-import-export/django-import-export/blob/main/docs/contributing.rst#development) and then code will be formatted correctly when you commit.

2023-10-27 11:12 UTC, matthewhegarty commented on tests/core/tests/admin_integration/test_action.py
> +from tests.core.tests.admin_integration.test_admin_integration import AdminTestMixin
I think it is better to import as follows:

```
from core.tests.admin_integration.test_admin_integration import AdminTestMixin
```

(applies to other files as well)

2023-10-27 11:14 UTC, matthewhegarty requested changes
Looks really good.  I have made a couple of minor comments.

2023-10-27 11:14 UTC, matthewhegarty commented on tests/core/tests/admin_integration/test_admin_integration.py
> +class AdminTestMixin(object):
This file contains a mixin and no tests, therefore I think the file should be renamed as `mixins.py`

2023-10-27 11:15 UTC, matthewhegarty commented
@PrashansaChaudhary You can also update AUTHORS with your name if you like, and also updated changelog.rst

2023-10-28 11:39 UTC, matthewhegarty commented
Looks great, nearly there... All that's left to do:

- Reformat the code with [`pre-commit`](https://github.com/django-import-export/django-import-export/pull/1662#issuecomment-1782520455), then push again
- Add your name or username to `AUTHORS` (optional)
- Add a row to `CHANGELOG.rst`, something like
  - 'Refactored `test_admin_integration`: split into smaller test modules (#1662)'

Let me know if you need any guidance with this.

2023-10-30 18:52 UTC, matthewhegarty requested changes
Some minor changes please

2023-10-30 18:52 UTC, matthewhegarty commented on AUTHORS
> +-   Glay00 (Gleb Gorelov)
It looks like you have modified all lines here, you should only add your name on a new line.  Please can you revert and submit again.

2023-10-30 18:52 UTC, matthewhegarty commented on docs/changelog.rst
> +- Refactored test_admin_integration: split into smaller test modules (# 1662)
please remove the whitespace so that the line renders correctly i.e. change (# 1662) to (#1662)

2023-10-30 19:01 UTC, PrashansaChaudhary commented
I didnt mean to change the format for each line. My Vscode automatically formated the file which indirectly made the changes. I have made the requested changes to the file. Sorry for the trouble and thank you for your kind response

2023-10-30 19:03 UTC, matthewhegarty commented
It's no trouble, thanks for taking the time to work on this.  All looks good.  Once the tests pass I will merge.

2023-10-30 19:26 UTC, merged