refactor: split test_resources.py into sub-modules
django-import-export/django-import-export pull request #1704
Opened 2023-12-05 22:18 UTC by abastola0

Closes #1700

2023-12-06 07:14 UTC, matthewhegarty requested changes
Thanks for looking into this.

When I run the test suite for release-4 branch I see that 495 tests run.  In your branch there are only 301.

This is likely because your test modules should be named `test_` ([docs](https://docs.djangoproject.com/en/4.2/topics/testing/overview/#running-tests)).  Please can you correct this so that the correct number of tests run.

I also see test errors when running, so please can you address those.

Please also review contributing.rst and install pre-commit so that your files are formatted correctly.

Feel free to update changelog.rst and add your name to AUTHORS (optional).

2023-12-06 22:36 UTC, matthewhegarty commented on tests/core/tests/test_resources/test_modelresource/test_import.py
> +from ....models import Book
Please can you use this pattern (other files also to be update as well)

```
from core.models import Book
```

2023-12-09 12:39 UTC, matthewhegarty commented
@abastola0 Can you confirm you are still able to work on this?  If not, I will assign to another dev.  Thanks

2023-12-09 16:14 UTC, abastola0 commented
Yes i am working on it. Will make the changes by tomorrow.

2023-12-09 16:30 UTC, matthewhegarty commented
OK thanks - there is no immediate rush, so you can take your time if you wish.

2024-01-08 15:40 UTC, matthewhegarty commented
Superseded by #1733

2024-01-08 15:40 UTC, closed without merging