Refactored test_resources.py into test_modelresources package #1700
django-import-export/django-import-export pull request #1733
Opened 2024-01-07 03:57 UTC by bvedang

**Problem**

What problem have you solved?

The `test_resources.py` module exceeded 1.8k lines, becoming difficult to navigate and manage over time as more resource tests were added.

**Solution**

How did you solve the problem?

- Added `test_modelresources` package

- Split `ModelResource` tests into multiple classes.

**Acceptance Criteria**

Have you written tests? Have you included screenshots of your changes if applicable?
Did you document your changes? 

Tests executed against test_resources package to confirm no change in overall coverage or results.
No UI or documentation changes were required for this strictly organizational refactor.

2024-01-08 15:25 UTC, matthewhegarty requested changes
Thanks for doing this.  It is much better to have smaller modules like you have added.  I have made a couple of comments which I think would improve the PR.

2024-01-08 15:25 UTC, matthewhegarty commented on tests/core/tests/test_resources/test_modelresource/test_data_deletion_dry_run.py
> +class DataDeletionDryRunTests(TestCase):
Please can we keep the convention of using "Test" not "Tests".  For example, I prefer that this name is `DataDeletionDryRunTest`.  Please can you modify other test cases to end with `Test` and not `Tests`

2024-01-08 23:34 UTC, bvedang commented on tests/core/tests/test_resources/test_modelresource/test_data_deletion_dry_run.py
> +    def test_import_data_delete(self):
Certainly, your suggestion to rename the module to` test_data_deletion.py `makes sense, especially if not all tests within the `test_data_deletion_dry_run.py` module use the dry run approach. It's indeed important to have module names that accurately reflect the tests they contain. I have tried to name files based on the specific tests they are intended to perform, but I appreciate your input on this. I will review the module names and make sure they align more closely with the tests they include. Thank you for bringing this to my attention.

2024-01-09 11:12 UTC, matthewhegarty commented on tests/core/tests/test_resources/test_modelresource/test_data_deletion_dry_run.py
> +    def test_import_data_delete(self):
Thanks - please let me know when you would like me to review

2024-01-09 22:25 UTC, bvedang commented
Hi @matthewhegarty 

I have removed the `s` from the class name in updated refactored test classes as per the instruction and also rename the file s

2024-01-12 02:02 UTC, bvedang commented
Sure, thank you for resolving the conflicts

2024-01-13 13:00 UTC, matthewhegarty commented
I'm happy to merge this as it is.  I would like to do so soon because it is blocking other work.  I will hold off if you want to make more changes.  Please can you let me know.

2024-01-13 15:10 UTC, bvedang commented
Hi @matthewhegarty , I was trying to figure out what do i need to take care of, i am confused. Can you help me with it
Thank you

2024-01-13 15:31 UTC, matthewhegarty commented
Hi - it's all good - I will merge.  Thanks for all your help.

2024-01-13 15:37 UTC, merged