Fix indentation for skip_row docstring
django-import-export/django-import-export pull request #1743
Opened 2024-01-20 10:49 UTC by ulliholtgrave

Without the newline before the code block intersphinx isn't able to parse the docstring. I also adjusted the indentation of the block and propose to use the python environment for the code block.

**Problem**

[Intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) isn't able to parse the docstring for `skip_row` which is results in failing documentation builds.
Related issue: #1742 

**Solution**

I added a newline before the code block and optionally adjusted the indentation and code environment of the block.

2024-01-20 10:54 UTC, matthewhegarty commented
Thanks for submitting.  Feel free to add your name to `AUTHORS` and an update to `CHANGELOG.rst` would be appreciated.

2024-01-20 10:55 UTC, matthewhegarty requested changes
One minor comment re line length

2024-01-20 10:55 UTC, matthewhegarty commented on import_export/resources.py
> +                def skip_row(self, instance, original, row, import_validation_errors=None):
pre-commit failing with:

```
import_export/resources.py:651:89: E501 line too long (91 > 88 characters)
```

2024-01-20 16:26 UTC, ulliholtgrave commented
@matthewhegarty Thanks for the quick response. I think I applied the changes for the check. I also found some more indentation issues that intersphinx wasn't happy about. If you run your setup on `--nitpick` mode this also breaks.

2024-01-20 16:48 UTC, ulliholtgrave commented
I already saw the failed test. Will look into it :)

2024-01-20 16:56 UTC, matthewhegarty commented
Thanks.  I couldn't run with `nitpicky` - it didn't work for me, even when I installed the dev version of Sphinx.  Please could you raise a new issue which shows how to repeat the break with nitpicky?

2024-01-23 19:59 UTC, matthewhegarty commented
Hi - any chance you could look into this so I can get the fix into the next release.
Many thanks

2024-01-25 17:36 UTC, matthewhegarty commented
np - thanks for taking this on, much appreciated.

2024-02-01 10:31 UTC, matthewhegarty commented
Thank you - will merge

2024-02-01 10:32 UTC, merged