Fix #1793 and test creating widgets for model fields
django-import-export/django-import-export pull request #1795
Opened 2024-04-24 19:29 UTC by mishka251

**Problem**

Issue #1793. Model resource does not creating widgets for some model field classes.

**Solution**

- [x] create test
- [x] create solution
- [ ] write docs. Not needed

Add a test that checks whether a special widget is being created for each of the types of model fields. I hope it can help to find similar problems with another fields.

**Acceptance Criteria**

Have you written tests? Yes

Have you included screenshots of your changes if applicable? Not needed, no UI changes

Did you document your changes? Test has comments and doc strings. There are no significant changes to the public API.

2024-04-25 09:31 UTC, matthewhegarty commented
Thanks for this, and the comprehensive tests.

I would like this to go into the forthcoming v4 release, so is it possible you could rebase onto `release-4`?

It would ideal if you could update `CHANGELOG.rst` and feel free to add your name to `AUTHORS`.

2024-04-25 19:17 UTC, mishka251 commented
Rebased and change target to `release-4`.

Changelog and authors updated.

2024-04-26 08:28 UTC, matthewhegarty requested changes
Thanks so much for submitting this PR.  I've reviewed and have some minor comments.

2024-04-26 08:28 UTC, matthewhegarty commented on tests/core/tests/test_model_resource_fields_generate_widgets.py
> +class TestImportExportBug(TestCase):
Please could you rename this to a more descriptive term?  Perhaps `TestFieldWidgetMapping`.

2024-04-26 08:28 UTC, matthewhegarty commented on tests/core/tests/test_model_resource_fields_generate_widgets.py
> +        if django.VERSION >= (4, 1):
Our minimum supported version is 4.2 so perhaps this check isn't necessary?

2024-04-26 08:28 UTC, matthewhegarty commented on tests/core/tests/test_model_resource_fields_generate_widgets.py
> +    def _collect_all_clas_children(self, cls):
should this be `cls` not `clas`?

2024-04-26 19:05 UTC, mishka251 commented
When I was solving conflicts with `release-4`, I wrote my changes in `4.0.0` is this correct?

2024-04-26 19:05 UTC, matthewhegarty commented
Yes, all good, thanks

2024-04-26 19:06 UTC, matthewhegarty approved these changes

2024-04-26 19:19 UTC, merged