Handle invalid confirm_form while importing
django-import-export/django-import-export pull request #1905
Opened 2024-07-11 10:11 UTC by AyushDharDubey

**Problem**

#1901

**Solution**

When the confirm_form is invalid, the user will now be redirected back to the confirm page, with confirm_form errors passed as context, ensuring that appropriate validation errors are presented to the user .

2024-07-11 11:07 UTC, matthewhegarty commented
Is it possible you can add an integration test to prove the fix?

2024-07-11 18:04 UTC, AyushDharDubey commented
Added tests.

2024-07-12 07:49 UTC, AyushDharDubey commented
I apologize for the failed checks earlier. This is my first PR on any open source project, and I was not familiar with tox until now. I have run the tests using tox in the [latest commit](https://github.com/django-import-export/django-import-export/pull/1905/commits/63f299296617202cbd9c351f279db5c53be53bc6), and it should be ready for review.

2024-07-20 14:36 UTC, matthewhegarty requested changes
Thanks for submitting. I have tested it manually and it works ok.

I would prefer that the test code is split out into its own test so that we can be clear about what is being tested.  Would you be able to do that?

thanks

2024-07-20 17:40 UTC, AyushDharDubey commented
Thank you for your feedback.

I have split the test code into a separate test to make it more clear.

Please let me know if there are any further improvements I can make.

2024-07-20 19:04 UTC, matthewhegarty approved these changes
Great, much appreciated, thank you.
Feel free to add your name to `AUTHORS` if not already.

2024-07-20 19:24 UTC, AyushDharDubey commented
Done.

On Sun, Jul 21, 2024, 12:34 AM Matt Hegarty ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Great, much appreciated, thank you.
> Feel free to add your name to AUTHORS if not already.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/django-import-export/django-import-export/pull/1905#pullrequestreview-2190043644>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BB46TWNKYNNVDE4SW46QDCLZNKYFPAVCNFSM6AAAAABKWU3CZGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCOJQGA2DGNRUGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> <django-import-export/django-import-export/pull/1905/review/2190043644@
> github.com>
>

2024-07-20 19:30 UTC, merged