Add __repr__ method to InvalidRow for improved debugging
django-import-export/django-import-export pull request #2003
Opened 2024-11-13 20:44 UTC by GreatBahram

**Problem**

What problem have you solved?
This commit introduces a `__repr__` method for InvalidRow, allowing exceptions to be more easily inspected during debugging.

**Solution**
Adding `__repr__` method :shrug: 

How did you solve the problem?

**Acceptance Criteria**

Have you written tests? Have you included screenshots of your changes if applicable?
Did you document your changes?

2024-11-13 20:46 UTC, GreatBahram commented on import_export/results.py
> +            f"<{type(self).__name__}(row={self.number}, "
> [!NOTE]
> Here I assumed the number is representing the row, right?

2024-11-14 13:08 UTC, matthewhegarty commented on import_export/results.py
> +            f"<{type(self).__name__}(row={self.number}, "
yes, it is the row number.

2024-11-18 15:24 UTC, matthewhegarty requested changes
Hi - if you can fix the test as suggested I will merge.
thanks

2024-11-18 15:24 UTC, matthewhegarty commented on tests/core/tests/test_results.py
> +            repr(error), "<InvalidRow(row=1, error='invalid row', error_count=1)>"
You need to change this line to the following for the test to pass:

```python
        self.assertEqual(
            repr(error),
            (
                "<InvalidRow(row=1, error=ValidationError(['invalid row']), "
                "error_count=1)>"
            ),
        )
```

2024-11-19 11:18 UTC, GreatBahram commented on import_export/results.py
> +            f"<{type(self).__name__}(row={self.number}, "
Thanks :sunflower:

2024-11-19 14:29 UTC, matthewhegarty approved these changes

2024-11-19 14:29 UTC, merged

2024-11-19 14:30 UTC, matthewhegarty commented
Thanks for submitting